apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pf-microservices-template-first
  labels:
    service: pf-authentication-service
spec:
  maxUnavailable: "60%"
  selector:
    matchLabels:
      service: pf-microservices-template-first
