outputs:
  update-manifest-env:
    description: "Output the environment of the committed manifest."
    value: ${{ steps.check.outputs.manifest-env }}

runs:
  using: "file-confirm"
  steps:
    - id: check
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/script.sh
        BEFORE_SHA=$(jq -r '.before' $GITHUB_EVENT_PATH)
        AFTER_SHA=$(jq -r '.after' $GITHUB_EVENT_PATH)
        COMMIT_DIR_COUNT=$(git diff --name-only ${BEFORE_SHA} ${AFTER_SHA} | awk -F/ '{print $1}' | uniq | wc -l)
        COMMIT_MANIFEST_TYPE_COUNT=$(git diff --name-only ${BEFORE_SHA} ${AFTER_SHA} | awk -F/ '{print $2}' | uniq | wc -l)
        COMMIT_ENVIROMENT_COUNT=$(git diff --name-only ${BEFORE_SHA} ${AFTER_SHA} | awk -F/ '{print $3}' | uniq | wc -l)
        if [ ${COMMIT_DIR_COUNT} -ne 1 ]; then
          echo "Commit constraint violation : The project limit to commit is one."
          exit 1
        elif [ ${COMMIT_MANIFEST_TYPE_COUNT} -ne 1 ]; then
          echo "Commit constraint violation : There is only one manifest type to change."
          exit 1
        elif [ ${COMMIT_ENVIROMENT_COUNT} -ne 1 ]; then
          echo "Commit constraint violation : Only one environment can be changed."
          exit 1
        else
          COMMIT_ENVIROMENT_NAME=$(git diff --name-only ${BEFORE_SHA} ${AFTER_SHA} | awk -F/ '{print $3}' | uniq)
          echo "::set-output name=manifest-env::$COMMIT_ENVIROMENT_NAME"
        fi


        