outputs:
  update-manifest-env:
    description: "Output the environment of the committed manifest."
    value: ${{ steps.check.outputs.manifest-env }}
  pr-comment:
    description: "Output of the content to comment on PR."
    value: ${{ steps.check.outputs.pr-comment}}

runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      run: |
        echo "${GITHUB_EVENT_PATH}"
        BEFORE_SHA=$(jq -r '.pull_request.base.sha' $GITHUB_EVENT_PATH)
        echo "BEFORE_SHA: ${BEFORE_SHA}"
        AFTER_SHA=$(jq -r '.pull_request.head.sha' $GITHUB_EVENT_PATH)
        echo "AFTER_SHA: ${AFTER_SHA}"
        COMMIT_DIR_COUNT=$(git diff --name-only ${BEFORE_SHA} ${AFTER_SHA} | awk -F/ '{print $1}' | uniq | wc -l)
        echo "COMMIT_DIR_COUNT: ${COMMIT_DIR_COUNT}"
        COMMIT_MANIFEST_TYPE_COUNT=$(git diff --name-only ${BEFORE_SHA} ${AFTER_SHA} | awk -F/ '{print $2}' | uniq | wc -l)
        echo "COMMIT_MANIFEST_TYPE_COUNT: ${COMMIT_MANIFEST_TYPE_COUNT}"
        COMMIT_ENVIROMENT_COUNT=$(git diff --name-only ${BEFORE_SHA} ${AFTER_SHA} | awk -F/ '{print $3}' | uniq | wc -l)
        echo "COMMIT_ENVIROMENT_COUNT: ${COMMIT_ENVIROMENT_COUNT}"
        if [ ${COMMIT_DIR_COUNT} -ne 1 ]; then
          COMMIT_COMMENT="Commit constraint violation : The project limit to commit is one."
          echo "::set-output name=pr-comment::$COMMIT_COMMENT"
          echo "AAAA ${COMMIT_COMMENT}"
          exit 1
        elif [ ${COMMIT_MANIFEST_TYPE_COUNT} -ne 1 ]; then
          COMMIT_COMMENT="Commit constraint violation : There is only one manifest type to change."
          echo "::set-output name=pr-comment::$COMMIT_COMMENT"
          echo "AAAA ${COMMIT_COMMENT}"
          exit 1
        elif [ ${COMMIT_ENVIROMENT_COUNT} -ne 1 ]; then
          COMMIT_COMMENT="Commit constraint violation : Only one environment can be changed."
          echo "::set-output name=pr-comment::$COMMIT_COMMENT"
          echo "AAAA ${COMMIT_COMMENT}"
          exit 1
        else
          COMMIT_ENVIROMENT_NAME=$(git diff --name-only ${BEFORE_SHA} ${AFTER_SHA} | awk -F/ '{print $3}' | uniq)
          COMMIT_COMMENT="OK. (´・ω・`)"
          echo "::set-output name=pr-comment::$COMMIT_COMMENT"
          echo "::set-output name=manifest-env::$COMMIT_ENVIROMENT_NAME"
          echo "AAAA ${COMMIT_COMMENT}"
        fi
