apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: iwasaki-1
  labels:
    service: pf-authentication-service
spec:
  maxUnavailable: "60%"
  selector:
    matchLabels:
      service: iwasaki-1
