name: Auto Release branch create

on:
  push:
    branches:
      - master

jobs:
  auto-branch-create:
    name: "Release branch create"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: unix_time
        name: Get Date
        run: |
          U_TIME=$(date +%s%3N)
          echo "::set-output name=u_time::$U_TIME"
      - id: release_target
        name: Get Release Target branch
        run: |
          GET_BRANCH=${GITHUB_REF#refs/heads/}
          echo ${GET_BRANCH}
          elif [ ${GET_BRANCH} == "master" ]; then
            TARGET_BRANCH="stg"
          elif [ ${GET_BRANCH} == "rc" ]; then
            TARGET_BRANCH="stg"
          elif [ ${GET_BRANCH} == "stg" ]; then
            TARGET_BRANCH="master"
          else
            echo "CI is running from an untargeted branch."
            exit 1
          fi
          echo "::set-output name=r_branch::$TARGET_BRANCH"
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          branch: 'release/${{ steps.release_target.outputs.r_branch }}-${{ steps.unix_time.outputs.u_time }}'
