name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  commit-judgment:
    name: "check job run"
    runs-on: ubuntu-latest
    outputs:
      commit-environment-name: "${{steps.check.outputs.commit-environment-name}}"
      commit-dir-name: "${{steps.check.outputs.commit-dir-name}}"
      commit-judgment-name: "${{steps.check.outputs.commit-judgment-name}}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: check
        id: check
        uses: ./.github/actions/update-confirm
  auto-deploy-labo:
    name: "Auto Deploy"
    runs-on: ubuntu-latest
    needs: commit-judgment
    if: "contains(needs.commit-judgment.outputs.commit-judgment-name, 'run-manifests')"
    environment: stg
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: test
        run: |
          echo "${{github.ref}}"

