name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  auto-deploy-labo:
    name: "Auto Deploy"
    environment: stg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build -t test:test ./

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
      - name: Authenticate cloud SDK
        run: |
          gcloud --quiet auth configure-docker
          gcloud auth list
