name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  auto-deploy-labo:
    name: "Auto Deploy"
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: test
        run: |
          echo "${{github.head_ref}}"
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
      - name: check
        id: check
        uses: ./.github/actions/update-confirm
      - name: spinnaker-deploy-webhook-request
        id: spinnaker-deploy-webhook-request
        uses: ./.github/actions/spinnaker-deploy
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          impersonate_service_account: ${{ secrets.GCP_IMPERSONATE_SA }}
          spinnaker_client_id: ${{ secrets.SPINNAKER_CLIENT_ID }}
          spinnaker_webhook_url: ${{ secrets.SPINNAKER_URL }}
          spinnaker_webhook_source: "test"
