name: Auto Release branch create

on:
  push:
    branches:
      - master

jobs:
  commit-judgment:
    name: "check job run"
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check
        id: check
        uses: ./.github/actions/update-confirm
  auto-branch-create:
    name: "Release branch create"
    runs-on: ubuntu-latest
    needs: commit-judgment
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: unix-time
        name: Get Date
        run: |
          U_TIME=$(date +%s%3N)
          echo "::set-output name=u-time::$U_TIME"
      - name: labo-release-create
        id: labo-release-create
        uses: ./.github/actions/git-cherry-pick
        with:
          cherry_branch_name: "release/labo/${{steps.unix-time.outputs.u-time}}"
          push_branch_name: "labo"




 
