name: Auto PR create

on:
  push:
    branches:
      - master



jobs:
  auto-pr-create:
    name: "Release PR create"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          branch: 'release/test'
