name: Auto Release branch create

on:
  push:
    branches:
      - master

jobs:
  auto-branch-create:
    name: "Release branch create"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: unix_time
        name: Get Date
        run: |
          U_TIME=$(date +%s%3N)
          echo "::set-output name=u_time::$U_TIME"
      - name: check
        id: check
        uses: ./.github/actions/update-confirm
      - uses: actions/checkout@v2
        with:
          ref: stg
      - name: Get Release Target branch
        run: |
          pwd
          git branch



