name: PR constraint check

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  pr-check:
    name: "PR constraint check"
    if: "! contains(github.head_ref, 'maintenance-sre/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check
        id: check
        uses: ./.github/actions/update-confirm
      - name: Post comments
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          URL: ${{ github.event.pull_request.comments_url }}
        run: |
          curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"${{ steps.check.outputs.pr-comment }} \"}" \
             ${URL}

