name: PR constraint check

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - .github

jobs:
  pr-check:
    name: "PR constraint check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check
        uses: ./.github/actions/update-confirm


