name: PR constraint check

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  pr-check:
    name: "PR constraint check"
    runs-on: ubuntu-latest
    if: "! contains(github.head_ref, 'maintenance-sre/')" || "! contains(github.head_ref, 'release/machine/')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check
        id: check
        uses: ./.github/actions/update-confirm
      - name: judgment
        id: judgment
        run: |
          if [ ${{steps.check.outputs.commit-dir-count}} -ne 1 ]; then
            COMMIT_COMMENT="Commit constraint violation : The project limit to commit is one."
            echo "::set-output name=pr-comment::$COMMIT_COMMENT"
            exit 1
          elif [ ${{steps.check.outputs.commit-manifest-type-count}} -ne 1 ]; then
            COMMIT_COMMENT="Commit constraint violation : There is only one manifest type to change."
            echo "::set-output name=pr-comment::$COMMIT_COMMENT"
            exit 1
          elif [ ${{steps.check.outputs.commit-environment-count}} -ne 1 ]; then
            COMMIT_COMMENT="Commit constraint violation : Only one environment can be changed."
            echo "::set-output name=pr-comment::$COMMIT_COMMENT"
            exit 1
          else
            COMMIT_COMMENT="OK.  :+1:"
            echo "::set-output name=pr-comment::$COMMIT_COMMENT"
          fi
      - name: Post comments
        if: always()
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          URL: ${{github.event.pull_request.comments_url}}
        run: |
          echo "${{ steps.judgment.outputs.pr-comment }}"
          curl -X POST \
             -H "Authorization: Bearer ${GITHUB_TOKEN}" \
             -H 'content-type: application/json' \
             -d "{\"body\": \"${{steps.judgment.outputs.pr-comment}} \"}" \
             ${URL}

