name: Scheduling the Generated Manifest validation test action

on:
  push:
    branches:
      - master
jobs:
  create-service-list:
    name: "Generated manifest directory to service list create"
    runs-on: ubuntu-latest
    outputs:
      service-list: "${{steps.create-list.outputs.service-list}}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: create-list
        id: create-list
        run: |
          SERVICE_LIST="[`ls -dm run-manifests/*`]"
          echo "${SERVICE_LIST}"
          echo "::set-output name=service-list::$SERVICE_LIST"

  manifest-k8s-api-test:
    name: "Manifest API test"
    runs-on: ubuntu-latest
    needs: [create-service-list]
    strategy:
      matrix:
        env: ${{fromJSON(needs.create-service-list.outputs.service-list)}}
    environment: stg
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/kustomize-setup
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
      - run: |
          gcloud container clusters get-credentials "${{secrets.GKE_CLUSTER}}" --zone "${{secrets.GKE_ZONE}}"
      - name: validation
        run: |
          echo "${{matrix.env}}"
          echo "${{needs.create-service-list.outputs.service-list}}"
          kubectl apply -f ${{matrix.env}}/stg/build-manifest.ymal --validate --dry-run=server 2>&1 > /dev/null